// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Users/victin/Desktop/code/any-ui/node_modules/.pnpm/dumi@2.1.5_4hsxtk6oasbjkegdjfzmcsblrm/node_modules/dumi/theme-default/slots/NotFound/index.js';
