name: docs-ci

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  pull_request:
    types:
      - 'opened'
      - 'synchronize'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        
#       - name: Get pnpm store directory
#         id: pnpm-cache
#         run: |
#           echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
          
#       - name: Setup pnpm cache
#         uses: actions/cache@v3.2.4
#         with:
#           path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
#           key: ${{ runner.os }}-pnpm-store-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
#           restore-keys: |
#             ${{ runner.os }}-pnpm-store-node${{ matrix.node-version }}-
            
      - name: Install dependencies
        run: pnpm i
        
      - name: Run build
        run: pnpm docs:build
      
      - name: aliyun-oss-website-action
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          folder: docs-dist
          accessKeyId: ${{ secrets.ACCESSKEYID }}
          accessKeySecret: ${{ secrets.ACCESSKEYSECRET }}
          bucket: any-ui
          endpoint: oss-cn-hangzhou.aliyuncs.com
#           skipSetting: true
      
